const IMAGES = {
  Oval2YellowGoldSinglePolished:
    require("../../assets/images/oval-2-yellow-gold-single-polished.jpg")
      .default,
  Oval25YellowGoldSinglePolished:
    require("../../assets/images/oval-2.5-yellow-gold-single-polished.jpg")
      .default,
  Oval3YellowGoldSinglePolished:
    require("../../assets/images/oval-3-yellow-gold-single-polished.jpg")
      .default,
  Oval35YellowGoldSinglePolished:
    require("../../assets/images/oval-3.5-yellow-gold-single-polished.jpg")
      .default,
  Oval4YellowGoldSinglePolished:
    require("../../assets/images/oval-4-yellow-gold-single-polished.jpg")
      .default,
  Oval45YellowGoldSinglePolished:
    require("../../assets/images/oval-4.5-yellow-gold-single-polished.jpg")
      .default,
  Oval5YellowGoldSinglePolished:
    require("../../assets/images/oval-5-yellow-gold-single-polished.jpg")
      .default,
  Oval55YellowGoldSinglePolished:
    require("../../assets/images/oval-5.5-yellow-gold-single-polished.jpg")
      .default,
  Oval6YellowGoldSinglePolished:
    require("../../assets/images/oval-6-yellow-gold-single-polished.jpg")
      .default,
  Oval65YellowGoldSinglePolished:
    require("../../assets/images/oval-6.5-yellow-gold-single-polished.jpg")
      .default,
  Oval7YellowGoldSinglePolished:
    require("../../assets/images/oval-7-yellow-gold-single-polished.jpg")
      .default,
  Oval75YellowGoldSinglePolished:
    require("../../assets/images/oval-7.5-yellow-gold-single-polished.jpg")
      .default,
  Oval8YellowGoldSinglePolished:
    require("../../assets/images/oval-8-yellow-gold-single-polished.jpg")
      .default,
  Oval85YellowGoldSinglePolished:
    require("../../assets/images/oval-8.5-yellow-gold-single-polished.jpg")
      .default,
  Oval9YellowGoldSinglePolished:
    require("../../assets/images/oval-9-yellow-gold-single-polished.jpg")
      .default,
  Oval95YellowGoldSinglePolished:
    require("../../assets/images/oval-9.5-yellow-gold-single-polished.jpg")
      .default,
  Oval10YellowGoldSinglePolished:
    require("../../assets/images/oval-10-yellow-gold-single-polished.jpg")
      .default,
  Oval2RoseGoldSinglePolished:
    require("../../assets/images/oval-2-rose-gold-single-polished.jpg").default,
  Oval25RoseGoldSinglePolished:
    require("../../assets/images/oval-2.5-rose-gold-single-polished.jpg")
      .default,
  Oval3RoseGoldSinglePolished:
    require("../../assets/images/oval-3-rose-gold-single-polished.jpg").default,
  Oval35RoseGoldSinglePolished:
    require("../../assets/images/oval-3.5-rose-gold-single-polished.jpg")
      .default,
  Oval4RoseGoldSinglePolished:
    require("../../assets/images/oval-4-rose-gold-single-polished.jpg").default,
  Oval45RoseGoldSinglePolished:
    require("../../assets/images/oval-4.5-rose-gold-single-polished.jpg")
      .default,
  Oval5RoseGoldSinglePolished:
    require("../../assets/images/oval-5-rose-gold-single-polished.jpg").default,
  Oval55RoseGoldSinglePolished:
    require("../../assets/images/oval-5.5-rose-gold-single-polished.jpg")
      .default,
  Oval6RoseGoldSinglePolished:
    require("../../assets/images/oval-6-rose-gold-single-polished.jpg").default,
  Oval65RoseGoldSinglePolished:
    require("../../assets/images/oval-6.5-rose-gold-single-polished.jpg")
      .default,
  Oval7RoseGoldSinglePolished:
    require("../../assets/images/oval-7-rose-gold-single-polished.jpg").default,
  Oval75RoseGoldSinglePolished:
    require("../../assets/images/oval-7.5-rose-gold-single-polished.jpg")
      .default,
  Oval8RoseGoldSinglePolished:
    require("../../assets/images/oval-8-rose-gold-single-polished.jpg").default,
  Oval85RoseGoldSinglePolished:
    require("../../assets/images/oval-8.5-rose-gold-single-polished.jpg")
      .default,
  Oval9RoseGoldSinglePolished:
    require("../../assets/images/oval-9-rose-gold-single-polished.jpg").default,
  Oval95RoseGoldSinglePolished:
    require("../../assets/images/oval-9.5-rose-gold-single-polished.jpg")
      .default,
  Oval10RoseGoldSinglePolished:
    require("../../assets/images/oval-10-rose-gold-single-polished.jpg")
      .default,
  Oval2WhiteGoldSinglePolished:
    require("../../assets/images/oval-2-white-gold-single-polished.jpg")
      .default,
  Oval25WhiteGoldSinglePolished:
    require("../../assets/images/oval-2.5-white-gold-single-polished.jpg")
      .default,
  Oval3WhiteGoldSinglePolished:
    require("../../assets/images/oval-3-white-gold-single-polished.jpg")
      .default,
  Oval35WhiteGoldSinglePolished:
    require("../../assets/images/oval-3.5-white-gold-single-polished.jpg")
      .default,
  Oval4WhiteGoldSinglePolished:
    require("../../assets/images/oval-4-white-gold-single-polished.jpg")
      .default,
  Oval45WhiteGoldSinglePolished:
    require("../../assets/images/oval-4.5-white-gold-single-polished.jpg")
      .default,
  Oval5WhiteGoldSinglePolished:
    require("../../assets/images/oval-5-white-gold-single-polished.jpg")
      .default,
  Oval55WhiteGoldSinglePolished:
    require("../../assets/images/oval-5.5-white-gold-single-polished.jpg")
      .default,
  Oval6WhiteGoldSinglePolished:
    require("../../assets/images/oval-6-white-gold-single-polished.jpg")
      .default,
  Oval65WhiteGoldSinglePolished:
    require("../../assets/images/oval-6.5-white-gold-single-polished.jpg")
      .default,
  Oval7WhiteGoldSinglePolished:
    require("../../assets/images/oval-7-white-gold-single-polished.jpg")
      .default,
  Oval75WhiteGoldSinglePolished:
    require("../../assets/images/oval-7.5-white-gold-single-polished.jpg")
      .default,
  Oval8WhiteGoldSinglePolished:
    require("../../assets/images/oval-8-white-gold-single-polished.jpg")
      .default,
  Oval85WhiteGoldSinglePolished:
    require("../../assets/images/oval-8.5-white-gold-single-polished.jpg")
      .default,
  Oval9WhiteGoldSinglePolished:
    require("../../assets/images/oval-9-white-gold-single-polished.jpg")
      .default,
  Oval95WhiteGoldSinglePolished:
    require("../../assets/images/oval-9.5-white-gold-single-polished.jpg")
      .default,
  Oval10WhiteGoldSinglePolished:
    require("../../assets/images/oval-10-white-gold-single-polished.jpg")
      .default,
  Elipse2YellowGoldSinglePolished:
    require("../../assets/images/elipse-2-yellow-gold-single-polished.jpg")
      .default,
  Elipse25YellowGoldSinglePolished:
    require("../../assets/images/elipse-2.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse3YellowGoldSinglePolished:
    require("../../assets/images/elipse-3-yellow-gold-single-polished.jpg")
      .default,
  Elipse35YellowGoldSinglePolished:
    require("../../assets/images/elipse-3.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse4YellowGoldSinglePolished:
    require("../../assets/images/elipse-4-yellow-gold-single-polished.jpg")
      .default,
  Elipse45YellowGoldSinglePolished:
    require("../../assets/images/elipse-4.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse5YellowGoldSinglePolished:
    require("../../assets/images/elipse-5-yellow-gold-single-polished.jpg")
      .default,
  Elipse55YellowGoldSinglePolished:
    require("../../assets/images/elipse-5.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse6YellowGoldSinglePolished:
    require("../../assets/images/elipse-6-yellow-gold-single-polished.jpg")
      .default,
  Elipse65YellowGoldSinglePolished:
    require("../../assets/images/elipse-6.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse7YellowGoldSinglePolished:
    require("../../assets/images/elipse-7-yellow-gold-single-polished.jpg")
      .default,
  Elipse75YellowGoldSinglePolished:
    require("../../assets/images/elipse-7.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse8YellowGoldSinglePolished:
    require("../../assets/images/elipse-8-yellow-gold-single-polished.jpg")
      .default,
  Elipse85YellowGoldSinglePolished:
    require("../../assets/images/elipse-8.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse9YellowGoldSinglePolished:
    require("../../assets/images/elipse-9-yellow-gold-single-polished.jpg")
      .default,
  Elipse95YellowGoldSinglePolished:
    require("../../assets/images/elipse-9.5-yellow-gold-single-polished.jpg")
      .default,
  Elipse10YellowGoldSinglePolished:
    require("../../assets/images/elipse-10-yellow-gold-single-polished.jpg")
      .default,
  Elipse2RoseGoldSinglePolished:
    require("../../assets/images/elipse-2-rose-gold-single-polished.jpg")
      .default,
  Elipse25RoseGoldSinglePolished:
    require("../../assets/images/elipse-2.5-rose-gold-single-polished.jpg")
      .default,
  Elipse3RoseGoldSinglePolished:
    require("../../assets/images/elipse-3-rose-gold-single-polished.jpg")
      .default,
  Elipse35RoseGoldSinglePolished:
    require("../../assets/images/elipse-3.5-rose-gold-single-polished.jpg")
      .default,
  Elipse4RoseGoldSinglePolished:
    require("../../assets/images/elipse-4-rose-gold-single-polished.jpg")
      .default,
  Elipse45RoseGoldSinglePolished:
    require("../../assets/images/elipse-4.5-rose-gold-single-polished.jpg")
      .default,
  Elipse5RoseGoldSinglePolished:
    require("../../assets/images/elipse-5-rose-gold-single-polished.jpg")
      .default,
  Elipse55RoseGoldSinglePolished:
    require("../../assets/images/elipse-5.5-rose-gold-single-polished.jpg")
      .default,
  Elipse6RoseGoldSinglePolished:
    require("../../assets/images/elipse-6-rose-gold-single-polished.jpg")
      .default,
  Elipse65RoseGoldSinglePolished:
    require("../../assets/images/elipse-6.5-rose-gold-single-polished.jpg")
      .default,
  Elipse7RoseGoldSinglePolished:
    require("../../assets/images/elipse-7-rose-gold-single-polished.jpg")
      .default,
  Elipse75RoseGoldSinglePolished:
    require("../../assets/images/elipse-7.5-rose-gold-single-polished.jpg")
      .default,
  Elipse8RoseGoldSinglePolished:
    require("../../assets/images/elipse-8-rose-gold-single-polished.jpg")
      .default,
  Elipse85RoseGoldSinglePolished:
    require("../../assets/images/elipse-8.5-rose-gold-single-polished.jpg")
      .default,
  Elipse9RoseGoldSinglePolished:
    require("../../assets/images/elipse-9-rose-gold-single-polished.jpg")
      .default,
  Elipse95RoseGoldSinglePolished:
    require("../../assets/images/elipse-9.5-rose-gold-single-polished.jpg")
      .default,
  Elipse10RoseGoldSinglePolished:
    require("../../assets/images/elipse-10-rose-gold-single-polished.jpg")
      .default,
  Elipse2WhiteGoldSinglePolished:
    require("../../assets/images/elipse-2-white-gold-single-polished.jpg")
      .default,
  Elipse25WhiteGoldSinglePolished:
    require("../../assets/images/elipse-2.5-white-gold-single-polished.jpg")
      .default,
  Elipse3WhiteGoldSinglePolished:
    require("../../assets/images/elipse-3-white-gold-single-polished.jpg")
      .default,
  Elipse35WhiteGoldSinglePolished:
    require("../../assets/images/elipse-3.5-white-gold-single-polished.jpg")
      .default,
  Elipse4WhiteGoldSinglePolished:
    require("../../assets/images/elipse-4-white-gold-single-polished.jpg")
      .default,
  Elipse45WhiteGoldSinglePolished:
    require("../../assets/images/elipse-4.5-white-gold-single-polished.jpg")
      .default,
  Elipse5WhiteGoldSinglePolished:
    require("../../assets/images/elipse-5-white-gold-single-polished.jpg")
      .default,
  Elipse55WhiteGoldSinglePolished:
    require("../../assets/images/elipse-5.5-white-gold-single-polished.jpg")
      .default,
  Elipse6WhiteGoldSinglePolished:
    require("../../assets/images/elipse-6-white-gold-single-polished.jpg")
      .default,
  Elipse65WhiteGoldSinglePolished:
    require("../../assets/images/elipse-6.5-white-gold-single-polished.jpg")
      .default,
  Elipse7WhiteGoldSinglePolished:
    require("../../assets/images/elipse-7-white-gold-single-polished.jpg")
      .default,
  Elipse75WhiteGoldSinglePolished:
    require("../../assets/images/elipse-7.5-white-gold-single-polished.jpg")
      .default,
  Elipse8WhiteGoldSinglePolished:
    require("../../assets/images/elipse-8-white-gold-single-polished.jpg")
      .default,
  Elipse85WhiteGoldSinglePolished:
    require("../../assets/images/elipse-8.5-white-gold-single-polished.jpg")
      .default,
  Elipse9WhiteGoldSinglePolished:
    require("../../assets/images/elipse-9-white-gold-single-polished.jpg")
      .default,
  Elipse95WhiteGoldSinglePolished:
    require("../../assets/images/elipse-9.5-white-gold-single-polished.jpg")
      .default,
  Elipse10WhiteGoldSinglePolished:
    require("../../assets/images/elipse-10-white-gold-single-polished.jpg")
      .default,
  Parabel2YellowGoldSinglePolished:
    require("../../assets/images/parabel-2-yellow-gold-single-polished.jpg")
      .default,
  Parabel25YellowGoldSinglePolished:
    require("../../assets/images/parabel-2.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel3YellowGoldSinglePolished:
    require("../../assets/images/parabel-3-yellow-gold-single-polished.jpg")
      .default,
  Parabel35YellowGoldSinglePolished:
    require("../../assets/images/parabel-3.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel4YellowGoldSinglePolished:
    require("../../assets/images/parabel-4-yellow-gold-single-polished.jpg")
      .default,
  Parabel45YellowGoldSinglePolished:
    require("../../assets/images/parabel-4.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel5YellowGoldSinglePolished:
    require("../../assets/images/parabel-5-yellow-gold-single-polished.jpg")
      .default,
  Parabel55YellowGoldSinglePolished:
    require("../../assets/images/parabel-5.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel6YellowGoldSinglePolished:
    require("../../assets/images/parabel-6-yellow-gold-single-polished.jpg")
      .default,
  Parabel65YellowGoldSinglePolished:
    require("../../assets/images/parabel-6.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel7YellowGoldSinglePolished:
    require("../../assets/images/parabel-7-yellow-gold-single-polished.jpg")
      .default,
  Parabel75YellowGoldSinglePolished:
    require("../../assets/images/parabel-7.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel8YellowGoldSinglePolished:
    require("../../assets/images/parabel-8-yellow-gold-single-polished.jpg")
      .default,
  Parabel85YellowGoldSinglePolished:
    require("../../assets/images/parabel-8.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel9YellowGoldSinglePolished:
    require("../../assets/images/parabel-9-yellow-gold-single-polished.jpg")
      .default,
  Parabel95YellowGoldSinglePolished:
    require("../../assets/images/parabel-9.5-yellow-gold-single-polished.jpg")
      .default,
  Parabel10YellowGoldSinglePolished:
    require("../../assets/images/parabel-10-yellow-gold-single-polished.jpg")
      .default,
  Parabel2RoseGoldSinglePolished:
    require("../../assets/images/parabel-2-rose-gold-single-polished.jpg")
      .default,
  Parabel25RoseGoldSinglePolished:
    require("../../assets/images/parabel-2.5-rose-gold-single-polished.jpg")
      .default,
  Parabel3RoseGoldSinglePolished:
    require("../../assets/images/parabel-3-rose-gold-single-polished.jpg")
      .default,
  Parabel35RoseGoldSinglePolished:
    require("../../assets/images/parabel-3.5-rose-gold-single-polished.jpg")
      .default,
  Parabel4RoseGoldSinglePolished:
    require("../../assets/images/parabel-4-rose-gold-single-polished.jpg")
      .default,
  Parabel45RoseGoldSinglePolished:
    require("../../assets/images/parabel-4.5-rose-gold-single-polished.jpg")
      .default,
  Parabel5RoseGoldSinglePolished:
    require("../../assets/images/parabel-5-rose-gold-single-polished.jpg")
      .default,
  Parabel55RoseGoldSinglePolished:
    require("../../assets/images/parabel-5.5-rose-gold-single-polished.jpg")
      .default,
  Parabel6RoseGoldSinglePolished:
    require("../../assets/images/parabel-6-rose-gold-single-polished.jpg")
      .default,
  Parabel65RoseGoldSinglePolished:
    require("../../assets/images/parabel-6.5-rose-gold-single-polished.jpg")
      .default,
  Parabel7RoseGoldSinglePolished:
    require("../../assets/images/parabel-7-rose-gold-single-polished.jpg")
      .default,
  Parabel75RoseGoldSinglePolished:
    require("../../assets/images/parabel-7.5-rose-gold-single-polished.jpg")
      .default,
  Parabel8RoseGoldSinglePolished:
    require("../../assets/images/parabel-8-rose-gold-single-polished.jpg")
      .default,
  Parabel85RoseGoldSinglePolished:
    require("../../assets/images/parabel-8.5-rose-gold-single-polished.jpg")
      .default,
  Parabel9RoseGoldSinglePolished:
    require("../../assets/images/parabel-9-rose-gold-single-polished.jpg")
      .default,
  Parabel95RoseGoldSinglePolished:
    require("../../assets/images/parabel-9.5-rose-gold-single-polished.jpg")
      .default,
  Parabel10RoseGoldSinglePolished:
    require("../../assets/images/parabel-10-rose-gold-single-polished.jpg")
      .default,
  Parabel2WhiteGoldSinglePolished:
    require("../../assets/images/parabel-2-white-gold-single-polished.jpg")
      .default,
  Parabel25WhiteGoldSinglePolished:
    require("../../assets/images/parabel-2.5-white-gold-single-polished.jpg")
      .default,
  Parabel3WhiteGoldSinglePolished:
    require("../../assets/images/parabel-3-white-gold-single-polished.jpg")
      .default,
  Parabel35WhiteGoldSinglePolished:
    require("../../assets/images/parabel-3.5-white-gold-single-polished.jpg")
      .default,
  Parabel4WhiteGoldSinglePolished:
    require("../../assets/images/parabel-4-white-gold-single-polished.jpg")
      .default,
  Parabel45WhiteGoldSinglePolished:
    require("../../assets/images/parabel-4.5-white-gold-single-polished.jpg")
      .default,
  Parabel5WhiteGoldSinglePolished:
    require("../../assets/images/parabel-5-white-gold-single-polished.jpg")
      .default,
  Parabel55WhiteGoldSinglePolished:
    require("../../assets/images/parabel-5.5-white-gold-single-polished.jpg")
      .default,
  Parabel6WhiteGoldSinglePolished:
    require("../../assets/images/parabel-6-white-gold-single-polished.jpg")
      .default,
  Parabel65WhiteGoldSinglePolished:
    require("../../assets/images/parabel-6.5-white-gold-single-polished.jpg")
      .default,
  Parabel7WhiteGoldSinglePolished:
    require("../../assets/images/parabel-7-white-gold-single-polished.jpg")
      .default,
  Parabel75WhiteGoldSinglePolished:
    require("../../assets/images/parabel-7.5-white-gold-single-polished.jpg")
      .default,
  Parabel8WhiteGoldSinglePolished:
    require("../../assets/images/parabel-8-white-gold-single-polished.jpg")
      .default,
  Parabel85WhiteGoldSinglePolished:
    require("../../assets/images/parabel-8.5-white-gold-single-polished.jpg")
      .default,
  Parabel9WhiteGoldSinglePolished:
    require("../../assets/images/parabel-9-white-gold-single-polished.jpg")
      .default,
  Parabel95WhiteGoldSinglePolished:
    require("../../assets/images/parabel-9.5-white-gold-single-polished.jpg")
      .default,
  Parabel10WhiteGoldSinglePolished:
    require("../../assets/images/parabel-10-white-gold-single-polished.jpg")
      .default,
  Sidecut2YellowGoldSinglePolished:
    require("../../assets/images/sidecut-2-yellow-gold-single-polished.jpg")
      .default,
  Sidecut25YellowGoldSinglePolished:
    require("../../assets/images/sidecut-2.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut3YellowGoldSinglePolished:
    require("../../assets/images/sidecut-3-yellow-gold-single-polished.jpg")
      .default,
  Sidecut35YellowGoldSinglePolished:
    require("../../assets/images/sidecut-3.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut4YellowGoldSinglePolished:
    require("../../assets/images/sidecut-4-yellow-gold-single-polished.jpg")
      .default,
  Sidecut45YellowGoldSinglePolished:
    require("../../assets/images/sidecut-4.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut5YellowGoldSinglePolished:
    require("../../assets/images/sidecut-5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut55YellowGoldSinglePolished:
    require("../../assets/images/sidecut-5.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut6YellowGoldSinglePolished:
    require("../../assets/images/sidecut-6-yellow-gold-single-polished.jpg")
      .default,
  Sidecut65YellowGoldSinglePolished:
    require("../../assets/images/sidecut-6.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut7YellowGoldSinglePolished:
    require("../../assets/images/sidecut-7-yellow-gold-single-polished.jpg")
      .default,
  Sidecut75YellowGoldSinglePolished:
    require("../../assets/images/sidecut-7.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut8YellowGoldSinglePolished:
    require("../../assets/images/sidecut-8-yellow-gold-single-polished.jpg")
      .default,
  Sidecut85YellowGoldSinglePolished:
    require("../../assets/images/sidecut-8.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut9YellowGoldSinglePolished:
    require("../../assets/images/sidecut-9-yellow-gold-single-polished.jpg")
      .default,
  Sidecut95YellowGoldSinglePolished:
    require("../../assets/images/sidecut-9.5-yellow-gold-single-polished.jpg")
      .default,
  Sidecut10YellowGoldSinglePolished:
    require("../../assets/images/sidecut-10-yellow-gold-single-polished.jpg")
      .default,
  Sidecut2RoseGoldSinglePolished:
    require("../../assets/images/sidecut-2-rose-gold-single-polished.jpg")
      .default,
  Sidecut25RoseGoldSinglePolished:
    require("../../assets/images/sidecut-2.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut3RoseGoldSinglePolished:
    require("../../assets/images/sidecut-3-rose-gold-single-polished.jpg")
      .default,
  Sidecut35RoseGoldSinglePolished:
    require("../../assets/images/sidecut-3.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut4RoseGoldSinglePolished:
    require("../../assets/images/sidecut-4-rose-gold-single-polished.jpg")
      .default,
  Sidecut45RoseGoldSinglePolished:
    require("../../assets/images/sidecut-4.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut5RoseGoldSinglePolished:
    require("../../assets/images/sidecut-5-rose-gold-single-polished.jpg")
      .default,
  Sidecut55RoseGoldSinglePolished:
    require("../../assets/images/sidecut-5.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut6RoseGoldSinglePolished:
    require("../../assets/images/sidecut-6-rose-gold-single-polished.jpg")
      .default,
  Sidecut65RoseGoldSinglePolished:
    require("../../assets/images/sidecut-6.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut7RoseGoldSinglePolished:
    require("../../assets/images/sidecut-7-rose-gold-single-polished.jpg")
      .default,
  Sidecut75RoseGoldSinglePolished:
    require("../../assets/images/sidecut-7.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut8RoseGoldSinglePolished:
    require("../../assets/images/sidecut-8-rose-gold-single-polished.jpg")
      .default,
  Sidecut85RoseGoldSinglePolished:
    require("../../assets/images/sidecut-8.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut9RoseGoldSinglePolished:
    require("../../assets/images/sidecut-9-rose-gold-single-polished.jpg")
      .default,
  Sidecut95RoseGoldSinglePolished:
    require("../../assets/images/sidecut-9.5-rose-gold-single-polished.jpg")
      .default,
  Sidecut10RoseGoldSinglePolished:
    require("../../assets/images/sidecut-10-rose-gold-single-polished.jpg")
      .default,
  Sidecut2WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-2-white-gold-single-polished.jpg")
      .default,
  Sidecut25WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-2.5-white-gold-single-polished.jpg")
      .default,
  Sidecut3WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-3-white-gold-single-polished.jpg")
      .default,
  Sidecut35WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-3.5-white-gold-single-polished.jpg")
      .default,
  Sidecut4WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-4-white-gold-single-polished.jpg")
      .default,
  Sidecut45WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-4.5-white-gold-single-polished.jpg")
      .default,
  Sidecut5WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-5-white-gold-single-polished.jpg")
      .default,
  Sidecut55WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-5.5-white-gold-single-polished.jpg")
      .default,
  Sidecut6WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-6-white-gold-single-polished.jpg")
      .default,
  Sidecut65WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-6.5-white-gold-single-polished.jpg")
      .default,
  Sidecut7WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-7-white-gold-single-polished.jpg")
      .default,
  Sidecut75WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-7.5-white-gold-single-polished.jpg")
      .default,
  Sidecut8WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-8-white-gold-single-polished.jpg")
      .default,
  Sidecut85WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-8.5-white-gold-single-polished.jpg")
      .default,
  Sidecut9WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-9-white-gold-single-polished.jpg")
      .default,
  Sidecut95WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-9.5-white-gold-single-polished.jpg")
      .default,
  Sidecut10WhiteGoldSinglePolished:
    require("../../assets/images/sidecut-10-white-gold-single-polished.jpg")
      .default,
  Planar2YellowGoldSinglePolished:
    require("../../assets/images/planar-2-yellow-gold-single-polished.jpg")
      .default,
  Planar25YellowGoldSinglePolished:
    require("../../assets/images/planar-2.5-yellow-gold-single-polished.jpg")
      .default,
  Planar3YellowGoldSinglePolished:
    require("../../assets/images/planar-3-yellow-gold-single-polished.jpg")
      .default,
  Planar35YellowGoldSinglePolished:
    require("../../assets/images/planar-3.5-yellow-gold-single-polished.jpg")
      .default,
  Planar4YellowGoldSinglePolished:
    require("../../assets/images/planar-4-yellow-gold-single-polished.jpg")
      .default,
  Planar45YellowGoldSinglePolished:
    require("../../assets/images/planar-4.5-yellow-gold-single-polished.jpg")
      .default,
  Planar5YellowGoldSinglePolished:
    require("../../assets/images/planar-5-yellow-gold-single-polished.jpg")
      .default,
  Planar55YellowGoldSinglePolished:
    require("../../assets/images/planar-5.5-yellow-gold-single-polished.jpg")
      .default,
  Planar6YellowGoldSinglePolished:
    require("../../assets/images/planar-6-yellow-gold-single-polished.jpg")
      .default,
  Planar65YellowGoldSinglePolished:
    require("../../assets/images/planar-6.5-yellow-gold-single-polished.jpg")
      .default,
  Planar7YellowGoldSinglePolished:
    require("../../assets/images/planar-7-yellow-gold-single-polished.jpg")
      .default,
  Planar75YellowGoldSinglePolished:
    require("../../assets/images/planar-7.5-yellow-gold-single-polished.jpg")
      .default,
  Planar8YellowGoldSinglePolished:
    require("../../assets/images/planar-8-yellow-gold-single-polished.jpg")
      .default,
  Planar85YellowGoldSinglePolished:
    require("../../assets/images/planar-8.5-yellow-gold-single-polished.jpg")
      .default,
  Planar9YellowGoldSinglePolished:
    require("../../assets/images/planar-9-yellow-gold-single-polished.jpg")
      .default,
  Planar95YellowGoldSinglePolished:
    require("../../assets/images/planar-9.5-yellow-gold-single-polished.jpg")
      .default,
  Planar10YellowGoldSinglePolished:
    require("../../assets/images/planar-10-yellow-gold-single-polished.jpg")
      .default,
  Planar2RoseGoldSinglePolished:
    require("../../assets/images/planar-2-rose-gold-single-polished.jpg")
      .default,
  Planar25RoseGoldSinglePolished:
    require("../../assets/images/planar-2.5-rose-gold-single-polished.jpg")
      .default,
  Planar3RoseGoldSinglePolished:
    require("../../assets/images/planar-3-rose-gold-single-polished.jpg")
      .default,
  Planar35RoseGoldSinglePolished:
    require("../../assets/images/planar-3.5-rose-gold-single-polished.jpg")
      .default,
  Planar4RoseGoldSinglePolished:
    require("../../assets/images/planar-4-rose-gold-single-polished.jpg")
      .default,
  Planar45RoseGoldSinglePolished:
    require("../../assets/images/planar-4.5-rose-gold-single-polished.jpg")
      .default,
  Planar5RoseGoldSinglePolished:
    require("../../assets/images/planar-5-rose-gold-single-polished.jpg")
      .default,
  Planar55RoseGoldSinglePolished:
    require("../../assets/images/planar-5.5-rose-gold-single-polished.jpg")
      .default,
  Planar6RoseGoldSinglePolished:
    require("../../assets/images/planar-6-rose-gold-single-polished.jpg")
      .default,
  Planar65RoseGoldSinglePolished:
    require("../../assets/images/planar-6.5-rose-gold-single-polished.jpg")
      .default,
  Planar7RoseGoldSinglePolished:
    require("../../assets/images/planar-7-rose-gold-single-polished.jpg")
      .default,
  Planar75RoseGoldSinglePolished:
    require("../../assets/images/planar-7.5-rose-gold-single-polished.jpg")
      .default,
  Planar8RoseGoldSinglePolished:
    require("../../assets/images/planar-8-rose-gold-single-polished.jpg")
      .default,
  Planar85RoseGoldSinglePolished:
    require("../../assets/images/planar-8.5-rose-gold-single-polished.jpg")
      .default,
  Planar9RoseGoldSinglePolished:
    require("../../assets/images/planar-9-rose-gold-single-polished.jpg")
      .default,
  Planar95RoseGoldSinglePolished:
    require("../../assets/images/planar-9.5-rose-gold-single-polished.jpg")
      .default,
  Planar10RoseGoldSinglePolished:
    require("../../assets/images/planar-10-rose-gold-single-polished.jpg")
      .default,
  Planar2WhiteGoldSinglePolished:
    require("../../assets/images/planar-2-white-gold-single-polished.jpg")
      .default,
  Planar25WhiteGoldSinglePolished:
    require("../../assets/images/planar-2.5-white-gold-single-polished.jpg")
      .default,
  Planar3WhiteGoldSinglePolished:
    require("../../assets/images/planar-3-white-gold-single-polished.jpg")
      .default,
  Planar35WhiteGoldSinglePolished:
    require("../../assets/images/planar-3.5-white-gold-single-polished.jpg")
      .default,
  Planar4WhiteGoldSinglePolished:
    require("../../assets/images/planar-4-white-gold-single-polished.jpg")
      .default,
  Planar45WhiteGoldSinglePolished:
    require("../../assets/images/planar-4.5-white-gold-single-polished.jpg")
      .default,
  Planar5WhiteGoldSinglePolished:
    require("../../assets/images/planar-5-white-gold-single-polished.jpg")
      .default,
  Planar55WhiteGoldSinglePolished:
    require("../../assets/images/planar-5.5-white-gold-single-polished.jpg")
      .default,
  Planar6WhiteGoldSinglePolished:
    require("../../assets/images/planar-6-white-gold-single-polished.jpg")
      .default,
  Planar65WhiteGoldSinglePolished:
    require("../../assets/images/planar-6.5-white-gold-single-polished.jpg")
      .default,
  Planar7WhiteGoldSinglePolished:
    require("../../assets/images/planar-7-white-gold-single-polished.jpg")
      .default,
  Planar75WhiteGoldSinglePolished:
    require("../../assets/images/planar-7.5-white-gold-single-polished.jpg")
      .default,
  Planar8WhiteGoldSinglePolished:
    require("../../assets/images/planar-8-white-gold-single-polished.jpg")
      .default,
  Planar85WhiteGoldSinglePolished:
    require("../../assets/images/planar-8.5-white-gold-single-polished.jpg")
      .default,
  Planar9WhiteGoldSinglePolished:
    require("../../assets/images/planar-9-white-gold-single-polished.jpg")
      .default,
  Planar95WhiteGoldSinglePolished:
    require("../../assets/images/planar-9.5-white-gold-single-polished.jpg")
      .default,
  Planar10WhiteGoldSinglePolished:
    require("../../assets/images/planar-10-white-gold-single-polished.jpg")
      .default,
  Forma2YellowGoldSinglePolished:
    require("../../assets/images/forma-2-yellow-gold-single-polished.jpg")
      .default,
  Forma25YellowGoldSinglePolished:
    require("../../assets/images/forma-2.5-yellow-gold-single-polished.jpg")
      .default,
  Forma3YellowGoldSinglePolished:
    require("../../assets/images/forma-3-yellow-gold-single-polished.jpg")
      .default,
  Forma35YellowGoldSinglePolished:
    require("../../assets/images/forma-3.5-yellow-gold-single-polished.jpg")
      .default,
  Forma4YellowGoldSinglePolished:
    require("../../assets/images/forma-4-yellow-gold-single-polished.jpg")
      .default,
  Forma45YellowGoldSinglePolished:
    require("../../assets/images/forma-4.5-yellow-gold-single-polished.jpg")
      .default,
  Forma5YellowGoldSinglePolished:
    require("../../assets/images/forma-5-yellow-gold-single-polished.jpg")
      .default,
  Forma55YellowGoldSinglePolished:
    require("../../assets/images/forma-5.5-yellow-gold-single-polished.jpg")
      .default,
  Forma6YellowGoldSinglePolished:
    require("../../assets/images/forma-6-yellow-gold-single-polished.jpg")
      .default,
  Forma65YellowGoldSinglePolished:
    require("../../assets/images/forma-6.5-yellow-gold-single-polished.jpg")
      .default,
  Forma7YellowGoldSinglePolished:
    require("../../assets/images/forma-7-yellow-gold-single-polished.jpg")
      .default,
  Forma75YellowGoldSinglePolished:
    require("../../assets/images/forma-7.5-yellow-gold-single-polished.jpg")
      .default,
  Forma8YellowGoldSinglePolished:
    require("../../assets/images/forma-8-yellow-gold-single-polished.jpg")
      .default,
  Forma85YellowGoldSinglePolished:
    require("../../assets/images/forma-8.5-yellow-gold-single-polished.jpg")
      .default,
  Forma9YellowGoldSinglePolished:
    require("../../assets/images/forma-9-yellow-gold-single-polished.jpg")
      .default,
  Forma95YellowGoldSinglePolished:
    require("../../assets/images/forma-9.5-yellow-gold-single-polished.jpg")
      .default,
  Forma10YellowGoldSinglePolished:
    require("../../assets/images/forma-10-yellow-gold-single-polished.jpg")
      .default,
  Forma2RoseGoldSinglePolished:
    require("../../assets/images/forma-2-rose-gold-single-polished.jpg")
      .default,
  Forma25RoseGoldSinglePolished:
    require("../../assets/images/forma-2.5-rose-gold-single-polished.jpg")
      .default,
  Forma3RoseGoldSinglePolished:
    require("../../assets/images/forma-3-rose-gold-single-polished.jpg")
      .default,
  Forma35RoseGoldSinglePolished:
    require("../../assets/images/forma-3.5-rose-gold-single-polished.jpg")
      .default,
  Forma4RoseGoldSinglePolished:
    require("../../assets/images/forma-4-rose-gold-single-polished.jpg")
      .default,
  Forma45RoseGoldSinglePolished:
    require("../../assets/images/forma-4.5-rose-gold-single-polished.jpg")
      .default,
  Forma5RoseGoldSinglePolished:
    require("../../assets/images/forma-5-rose-gold-single-polished.jpg")
      .default,
  Forma55RoseGoldSinglePolished:
    require("../../assets/images/forma-5.5-rose-gold-single-polished.jpg")
      .default,
  Forma6RoseGoldSinglePolished:
    require("../../assets/images/forma-6-rose-gold-single-polished.jpg")
      .default,
  Forma65RoseGoldSinglePolished:
    require("../../assets/images/forma-6.5-rose-gold-single-polished.jpg")
      .default,
  Forma7RoseGoldSinglePolished:
    require("../../assets/images/forma-7-rose-gold-single-polished.jpg")
      .default,
  Forma75RoseGoldSinglePolished:
    require("../../assets/images/forma-7.5-rose-gold-single-polished.jpg")
      .default,
  Forma8RoseGoldSinglePolished:
    require("../../assets/images/forma-8-rose-gold-single-polished.jpg")
      .default,
  Forma85RoseGoldSinglePolished:
    require("../../assets/images/forma-8.5-rose-gold-single-polished.jpg")
      .default,
  Forma9RoseGoldSinglePolished:
    require("../../assets/images/forma-9-rose-gold-single-polished.jpg")
      .default,
  Forma95RoseGoldSinglePolished:
    require("../../assets/images/forma-9.5-rose-gold-single-polished.jpg")
      .default,
  Forma10RoseGoldSinglePolished:
    require("../../assets/images/forma-10-rose-gold-single-polished.jpg")
      .default,
  Forma2WhiteGoldSinglePolished:
    require("../../assets/images/forma-2-white-gold-single-polished.jpg")
      .default,
  Forma25WhiteGoldSinglePolished:
    require("../../assets/images/forma-2.5-white-gold-single-polished.jpg")
      .default,
  Forma3WhiteGoldSinglePolished:
    require("../../assets/images/forma-3-white-gold-single-polished.jpg")
      .default,
  Forma35WhiteGoldSinglePolished:
    require("../../assets/images/forma-3.5-white-gold-single-polished.jpg")
      .default,
  Forma4WhiteGoldSinglePolished:
    require("../../assets/images/forma-4-white-gold-single-polished.jpg")
      .default,
  Forma45WhiteGoldSinglePolished:
    require("../../assets/images/forma-4.5-white-gold-single-polished.jpg")
      .default,
  Forma5WhiteGoldSinglePolished:
    require("../../assets/images/forma-5-white-gold-single-polished.jpg")
      .default,
  Forma55WhiteGoldSinglePolished:
    require("../../assets/images/forma-5.5-white-gold-single-polished.jpg")
      .default,
  Forma6WhiteGoldSinglePolished:
    require("../../assets/images/forma-6-white-gold-single-polished.jpg")
      .default,
  Forma65WhiteGoldSinglePolished:
    require("../../assets/images/forma-6.5-white-gold-single-polished.jpg")
      .default,
  Forma7WhiteGoldSinglePolished:
    require("../../assets/images/forma-7-white-gold-single-polished.jpg")
      .default,
  Forma75WhiteGoldSinglePolished:
    require("../../assets/images/forma-7.5-white-gold-single-polished.jpg")
      .default,
  Forma8WhiteGoldSinglePolished:
    require("../../assets/images/forma-8-white-gold-single-polished.jpg")
      .default,
  Forma85WhiteGoldSinglePolished:
    require("../../assets/images/forma-8.5-white-gold-single-polished.jpg")
      .default,
  Forma9WhiteGoldSinglePolished:
    require("../../assets/images/forma-9-white-gold-single-polished.jpg")
      .default,
  Forma95WhiteGoldSinglePolished:
    require("../../assets/images/forma-9.5-white-gold-single-polished.jpg")
      .default,
  Forma10WhiteGoldSinglePolished:
    require("../../assets/images/forma-10-white-gold-single-polished.jpg")
      .default,
  SingleColored: require("../../assets/images/single-colored.jpg").default,
  BiColored1: require("../../assets/images/bi-colored-1.jpg").default,
  BiColored2: require("../../assets/images/bi-colored-2.jpg").default,
  BiColored3: require("../../assets/images/bi-colored-3.jpg").default,
  BiColored4: require("../../assets/images/bi-colored-4.jpg").default,
  TriColored1: require("../../assets/images/tri-colored-1.jpg").default,
  TriColored2: require("../../assets/images/tri-colored-2.jpg").default,
  TriColored3: require("../../assets/images/tri-colored-3.jpg").default,
  TriColored4: require("../../assets/images/tri-colored-4.jpg").default,
  TriColored5: require("../../assets/images/tri-colored-5.jpg").default,
  TriColored6: require("../../assets/images/tri-colored-6.jpg").default,
  TriColored7: require("../../assets/images/tri-colored-7.jpg").default,
  TriColored8: require("../../assets/images/tri-colored-8.jpg").default,
};

export default IMAGES;
